Cpatti ocw test pipeline
mitodl/ol-infrastructure pull request #2011
Opened 2023-12-19 21:13 UTC by feoh

# What are the relevant tickets?

Fixes #1945

# Description (What does it do?)

Adds end to end ocw testing buckets and Fastly nubbins to match.

2023-12-19 22:21 UTC, feoh commented
This apparently broke QA as written.

Please ***DO NOT MERGE***.

2023-12-20 14:27 UTC, blarghmatey requested changes

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{draft_bucket_arn}/*",
                    ],
```

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> -    cors_rules=[{"allowedMethods": ["GET", "HEAD"], "allowedOrigins": ["*"]}],
This needs to be maintained

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{test_bucket_arn}/*",
                    ],
```

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> -    cors_rules=[{"allowedMethods": ["GET", "HEAD"], "allowedOrigins": ["*"]}],
We want to maintain the cors rules as well

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{live_bucket_arn}/*",
                    ],
```

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{draft_backup_bucket_arn}/*",
                    ],
```

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> -    cors_rules=[{"allowedMethods": ["GET", "HEAD"], "allowedOrigins": ["*"]}],
Maintain the cors rules

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{live_backup_bucket_arn}/*",
                    ],
```

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{draft_offline_bucket_arn}/*",
                    ],
```

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{live_offline_bucket_arn}/*",
                    ],
```

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> -    cors_rules=[{"allowedMethods": ["GET", "HEAD"], "allowedOrigins": ["*"]}],
Maintain cors rules

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> -    website=s3.BucketWebsiteArgs(
We need to maintain these values as well

2023-12-20 14:27 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
```suggestion
                    "Principal": "*",
                    "Action": "s3:GetObject",
                    "Resource": [
                        f"{test_offline_bucket_arn}/*",
                    ],
```

2023-12-20 18:36 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
This bucket still needs the appropriate policy and CORS rules

2023-12-20 18:36 UTC, blarghmatey commented on src/ol_infrastructure/applications/ocw_site/__main__.py
> +                    ],
This bucket also still needs the proper policy applied.

2023-12-21 16:16 UTC, Ardiea commented
I setup a managed certificate in fastly for https://test-qa.ocw.mit.edu by hand but we should import that into pulumi and figure out how to do the DNS ownership verification automatically. 

https://manage.fastly.com/network/subscriptions/CaYUBzhqebsDvEuZLzATag

And then a CNAME in route53 

_acme-challenge.test-qa.ocw.mit.edu -> zmb1qhi6bx1nvgqsmb.fastly-validations.com

And then the existing CNAME for test-qa.ocw.mit.edu was pointing to j.sni.global.fastly.net but fastly said it should be pointing at d.sni.global.fastly.net so I changed that.

2023-12-21 19:10 UTC, blarghmatey approved these changes

2024-01-04 19:35 UTC, gumaerc commented
Sorry for the late comment here. I've been testing the new end to end testing pipeline in QA and everything is working great, but I have one question. In Vault, we have some secrets like `fastly_draft`, `fastly_live` in each environment. Can we add `fastly_test` to that and populate it with an API key like the others? This is important for cache clearing in between runs when there are changes.

2024-01-05 16:56 UTC, merged