refactor: Update MFE builds to include configurable plugin slot configs
mitodl/ol-infrastructure pull request #2866
Opened 2024-12-23 20:39 UTC by blarghmatey

### What are the relevant tickets?
https://github.com/mitodl/hq/issues/6261

### Description (What does it do?)

The newest method of customizing MFEs is through the use of plugin slots which are configured via a `.env.config.jsx` file that is present during the build. This updates the MFE build pipeline to allow for inclusion of those configs which are loaded from a separate repository.

### How can this be tested?

Apply the changes to the MFE pipeline in Concourse and verify that the CI builds have the appropriate modifications applied.

2024-12-24 12:55 UTC, asadali145 reviewed
I couldn't properly review the build steps.

I have left a suggestion to keep the config file naming generic to incorporate new slots and different configs for different MFEs.

2025-02-14 17:52 UTC, blarghmatey commented
This is ready for a proper review now. The changes have been verified working for the learning and learner-dashboard MFEs on lms-ci.mitx.mit.edu

2025-02-18 11:35 UTC, asadali145 commented on src/bridge/settings/openedx/mfe/learning_header.env.jsx
As per our [Slack discussion](https://mitodl.slack.com/archives/C083XQQ42AH/p1739547355363759), Is it better to keep these MFE config files here or in the smooth design?

CC: @ChristopherChudzicki

2025-02-18 11:37 UTC, asadali145 commented on src/bridge/settings/openedx/mfe/learning_header.env.jsx
Also, we will have to rename these as well. They won't have header only. These files can help us override different slots other than headers. Also, they will be different for different MFEs, like Learning MFE will have a different config file due to the different slots that we will/can override in future.

2025-02-18 14:00 UTC, asadali145 commented on src/bridge/settings/openedx/mfe/learning_header.env.jsx
> As per our [Slack discussion](https://mitodl.slack.com/archives/C083XQQ42AH/p1739547355363759), Is it better to keep these MFE config files here or in the smooth design?

My bad, I have discussed this with @ChristopherChudzicki and we want to keep the configs in here.

2025-02-20 15:06 UTC, asadali145 commented
@blarghmatey I just remembered that the env.config.jsx files that we have added in this PR are for the MITx Residential ONLY. They are not meant to be for MITx Online and MIT xPRO. In xpro and mitxonline, we have a different set of dropdown links in the UserMenu.

Whats the impact of this going to be on the changes of this PR?

2025-02-20 15:06 UTC, asadali145 commented
In MITx Residential, we only have dashboard and logout URLs, but in xpro and mitxonline, we have profile and settings/account URLs as well.

2025-02-20 15:14 UTC, asadali145 commented
They will have 2 extra URLs. Here is what the learning header config file looks like:
```
import { PLUGIN_OPERATIONS } from '@openedx/frontend-plugin-framework';
import { getConfig } from '@edx/frontend-platform';

const modifyUserMenu = (widget) => {
  widget.content.items = [
    {
      href: `${getConfig().LMS_BASE_URL}/dashboard`,
      message: 'Dashboard',
    },
    {
      href: `${getConfig().MARKETING_SITE_BASE_URL}/profile/`,
      message: 'Profile',
    },
    {
      href: `${getConfig().MARKETING_SITE_BASE_URL}/account-settings/`,
      message: 'Settings',
    },
    {
      href: `${getConfig().LMS_BASE_URL}/logout`,
      message: 'Sign Out',
    },
  ];
  return widget;
};

const config = {
  pluginSlots: {
    learning_user_menu_slot: {
      keepDefault: true,
      plugins: [
        {
          op: PLUGIN_OPERATIONS.Modify,
          widgetId: 'default_contents',
          fn: modifyUserMenu,
        },
      ],
    },
  },
};

export default config;
```

2025-02-20 15:14 UTC, asadali145 commented
For the other header it will be:
```
import { PLUGIN_OPERATIONS } from '@openedx/frontend-plugin-framework';
import { getConfig } from '@edx/frontend-platform';

const modifyUserMenu = (widget) => {
  widget.content.menu = [
    {
      items: [
        {
          type: 'item',
          href: `${getConfig().LMS_BASE_URL}/dashboard`,
          content: 'Dashboard',
        },
    {
      href: `${getConfig().MARKETING_SITE_BASE_URL}/profile/`,
      message: 'Profile',
    },
    {
      href: `${getConfig().MARKETING_SITE_BASE_URL}/account-settings/`,
      message: 'Settings',
    },
        {
          type: 'item',
          href: `${getConfig().LMS_BASE_URL}/logout`,
          content: 'Sign Out',
        },
      ],
    },
  ];
  return widget;
};

const config = {
  pluginSlots: {
    desktop_user_menu_slot: {
      keepDefault: true,
      plugins: [
        {
          op: PLUGIN_OPERATIONS.Modify,
          widgetId: 'default_contents',
          fn: modifyUserMenu,
        },
      ],
    },
  },
};

export default config;
```

2025-02-20 16:26 UTC, asadali145 requested changes

2025-02-20 16:26 UTC, asadali145 commented on src/bridge/settings/openedx/version_matrix.py
> -    "@edx/frontend-component-header@npm": (
We do not have a slot for the footer right now. Also, it is a work in progress by open edx. We should keep the footer override and remove the header override as that will be managed by the slots.

2025-02-20 16:26 UTC, asadali145 commented on src/bridge/settings/openedx/version_matrix.py
> -                    "@edx/brand@npm": "@mitodl/brand-mitol-residential@latest",
We also need to keep @edx/brand@npm override.

2025-02-20 16:55 UTC, blarghmatey commented on src/bridge/settings/openedx/version_matrix.py
> -                    "@edx/brand@npm": "@mitodl/brand-mitol-residential@latest",
Thanks for catching this, I just added it back.

2025-02-20 19:14 UTC, asadali145 approved these changes
LGTM! Thanks for the swift changes.

2025-02-20 20:29 UTC, merged